### ISSUE TITLE
[补充] napcat+stapxs+nginx wss 部署方式

### ISSUE THREAD

**Issue by PaSSw0rds** [Stapxs/Stapxs-QQ-Lite-2.0#245]
1. 生成自签名证书 （一路回车）
```
openssl genpkey -algorithm RSA -out server.key -pkeyopt rsa_keygen_bits:2048
openssl req -new -key server.key -out server.csr
openssl x509 -req -days 365 -in server.csr -signkey server.key -out server.crt
```
将生成后的所有server*文件存放到名为ssl的目录中

2. 准备 docker-compose.yml 
```
services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    restart: always
    network_mode: host

    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}

    volumes:
      - ./napcat/config:/app/napcat/config
      - ./ntqq:/app/.config/QQ

  nginx:
    container_name: napcat_nginx
    network_mode: host
    image: docker.io/bitnami/nginx:1.28
    volumes:
      - ./qq.conf:/opt/bitnami/nginx/conf/server_blocks/qq.conf:ro
      - ./ssl:/certs:ro
  stapxs:
    container_name: qq_web
    image: stapxs/qq-web:latest

    ports:
      - 8081:8080
```

3. 准备NGINX反代配置
```
  server {
    listen       8443 ssl;

    ssl_certificate      bitnami/certs/server.crt;
    ssl_certificate_key  bitnami/certs/server.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location / {
        proxy_pass http://127.0.0.1:3001;

        # WebSocket协议升级
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # 跨域设置（允许所有来源）
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept";

        # 其他代理头
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 86400;  # 长时间连接

    }
  }
```

4. 执行`NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) docker compose up -d`启动
5. 扫码登录，进入napcat后台开启websockt配置
6. 打开stapxs网页端，输入wss地址登录

![目录结构](https://github.com/user-attachments/assets/29571ac6-8a48-415f-85bc-956bccfe3f5d)

**Comment by Stapxs** [comment]
stapxs/qq-web 的容器其实就是个 nginx，把 ssl 和 nginx 配置直接挂进去就好（
再起个 Nginx 有点多余了 XD

ssqq 的文件在容器的 /usr/share/nginx/html 下，保留它的情况下再加点配置就好
（不过介于 nginx 本来就非常轻量其实也无所谓

https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/blob/240bb39426833224acfbec46a92d1b18b91db41e/dockerfile#L4-L12

**Comment by PaSSw0rds** [comment]
> stapxs/qq-web 的容器其实就是个 nginx，把 ssl 和 nginx 配置直接挂进去就好（ 再起个 Nginx 有点多余了 XD
> 
> ssqq 的文件在容器的 /usr/share/nginx/html 下，保留它的情况下再加点配置就好 （不过介于 nginx 本来就非常轻量其实也无所谓
> 
> [Stapxs-QQ-Lite-2.0/dockerfile](https://github.com/Stapxs/Stapxs-QQ-Lite-2.0/blob/240bb39426833224acfbec46a92d1b18b91db41e/dockerfile#L4-L12)
> 
> Lines 4 to 12 in [240bb39](/Stapxs/Stapxs-QQ-Lite-2.0/commit/240bb39426833224acfbec46a92d1b18b91db41e)
> 
>  FROM nginx:alpine 
>   
>  RUN rm -rf /usr/share/nginx/html/* 
>  COPY dist /usr/share/nginx/html 
>   
>  RUN sed -i 's/listen       80;/listen       8080;/' /etc/nginx/conf.d/default.conf 
>   
>  EXPOSE 8080 
>  CMD ["nginx", "-g", "daemon off;"]

这里用了很多端口，其实根本不需要的，容器之间搞通，可以指暴露最后一个nginx，只是懒得研究，给小白们的一个快速部署，毕竟容器化部署的话如果本地环境不一样，排查起来更麻烦…

**Comment by PaSSw0rds** [comment]
20250702 更新现行的配置，网页使用HTTPS才能使用chrome的通知能力

```
services:
  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    networks:
      - napcat-network
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}

    volumes:
      - ./napcat/config:/app/napcat/config
      - ./ntqq:/app/.config/QQ

  nginx:
    container_name: napcat_nginx
    image: docker.io/bitnami/nginx:1.28
    networks:
      - napcat-network
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./stapxs.conf:/opt/bitnami/nginx/conf/server_blocks/stapxs.conf:ro
      - ./qq.conf:/opt/bitnami/nginx/conf/server_blocks/qq.conf:ro
      - ./napcat.conf:/opt/bitnami/nginx/conf/server_blocks/napcat.conf:ro
      - ./ssl:/certs:ro
    ports:
      - 81:81
      - 82:82
      - 83:83
    depends_on:
      - napcat
      - stapxs

  stapxs:
    container_name: qq_web
    image: stapxs/qq-web:latest
    networks:
      - napcat-network
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  napcat-network:
    driver: bridge
```

---

stapxs.conf

```
  server {
    listen       81 ssl;

    ssl_certificate      bitnami/certs/server.crt;
    ssl_certificate_key  bitnami/certs/server.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;

    location / {
        proxy_pass http://stapxs:8080;
    }
  }
```

---

qq.conf

```
  server {
    listen       83 ssl;

    ssl_certificate      bitnami/certs/server.crt;
    ssl_certificate_key  bitnami/certs/server.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    location / {
        proxy_pass http://napcat:3001;

        # WebSocket协议升级
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # 跨域设置（允许所有来源）
        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept";

        # 其他代理头
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_read_timeout 86400;  # 长时间连接

    }
  }
```
